In [1]:
import pandas as pd

In [3]:
HI = pd.read_csv('data/Household Income LA County (2018).csv') 
#This command prompt loads the Social Explorer data file on Household Income in LA County into Jupyter Hub.

In [5]:
HI.shape

(2346, 88)

In [6]:
HI.head

<bound method NDFrame.head of         Geo_FIPS           Geo_GEOID              Geo_NAME  \
0     6037101110  14000US06037101110  Census Tract 1011.10
1     6037101122  14000US06037101122  Census Tract 1011.22
2     6037101210  14000US06037101210  Census Tract 1012.10
3     6037101220  14000US06037101220  Census Tract 1012.20
4     6037101300  14000US06037101300     Census Tract 1013
...          ...                 ...                   ...
2341  6037980031  14000US06037980031  Census Tract 9800.31
2342  6037980033  14000US06037980033  Census Tract 9800.33
2343  6037990100  14000US06037990100     Census Tract 9901
2344  6037990200  14000US06037990200     Census Tract 9902
2345  6037990300  14000US06037990300     Census Tract 9903

                                              Geo_QName Geo_STUSAB  \
0     Census Tract 1011.10, Los Angeles County, Cali...         ca
1     Census Tract 1011.22, Los Angeles County, Cali...         ca
2     Census Tract 1012.10, Los Angeles County, Cali...         ca
3     Census Tract 1012.20, Los Angeles County, Cali...         ca
4     Census Tract 1013, Los Angeles County, California         ca
...                                                 ...        ...
2341  Census Tract 9800.31, Los Angeles County, Cali...         ca
2342  Census Tract 9800.33, Los Angeles County, Cali...         ca
2343  Census Tract 9901, Los Angeles County, California         ca
2344  Census Tract 9902, Los Angeles County, California         ca
2345  Census Tract 9903, Los Angeles County, California         ca

      Geo_SUMLEV  Geo_GEOCOMP Geo_FILEID  Geo_LOGRECNO  Geo_US  ...  \
0            140            0      ACSSF          3870     NaN  ...
1            140            0      ACSSF          3871     NaN  ...
2            140            0      ACSSF          3872     NaN  ...
3            140            0      ACSSF          3873     NaN  ...
4            140            0      ACSSF          3874     NaN  ...
...          ...          ...        ...           ...     ...  ...
2341         140            0      ACSSF          6211     NaN  ...
2342         140            0      ACSSF          6212     NaN  ...
2343         140            0      ACSSF          6213     NaN  ...
2344         140            0      ACSSF          6214     NaN  ...
2345         140            0      ACSSF          6215     NaN  ...

      PCT_SE_A14001_008  PCT_SE_A14001_009  PCT_SE_A14001_010  \
0                  3.38               4.89               5.51
1                  0.56               3.18               1.83
2                  2.63               4.09               9.48
3                  4.64               9.12               9.51
4                  1.25               8.57               3.41
...                 ...                ...                ...
2341               0.00               0.00               0.00
2342               0.00               0.00               0.00
2343                NaN                NaN                NaN
2344                NaN                NaN                NaN
2345                NaN                NaN                NaN

      PCT_SE_A14001_011  PCT_SE_A14001_012  PCT_SE_A14001_013  \
0                  4.01               7.89              17.36
1                  4.94              14.81              18.47
2                  5.51               6.33               9.69
3                  4.10               5.80               6.80
4                  6.06               5.57              13.94
...                 ...                ...                ...
2341               0.00              62.50              16.67
2342               0.00               0.00               0.00
2343                NaN                NaN                NaN
2344                NaN                NaN                NaN
2345                NaN                NaN                NaN

      PCT_SE_A14001_014  PCT_SE_A14001_015  PCT_SE_A14001_016  \
0                  5.70               5.83               6.83
1                  9.08               8.36              10.59
2                  4.14               2.89               0.60
3                  8.50               3.48               3.32
4                 10.17               7.46              13.59
...                 ...                ...                ...
2341               0.00               0.00               0.00
2342               0.00               0.00               0.00
2343                NaN                NaN                NaN
2344                NaN                NaN                NaN
2345                NaN                NaN                NaN

      PCT_SE_A14001_017
0                  2.76
1                 15.29
2                  3.06
3                  3.01
4                 12.82
...                 ...
2341              20.83
2342               0.00
2343                NaN
2344                NaN
2345                NaN

[2346 rows x 88 columns]>

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
HI.sample()

,Geo_FIPS,Geo_GEOID,Geo_NAME,Geo_QName,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_FILEID,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_PLACESE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_BTTR,Geo_BTBG,Geo_PUMA5,Geo_PUMA1,SE_A14001_001,SE_A14001_002,SE_A14001_003,SE_A14001_004,SE_A14001_005,SE_A14001_006,SE_A14001_007,SE_A14001_008,SE_A14001_009,SE_A14001_010,SE_A14001_011,SE_A14001_012,SE_A14001_013,SE_A14001_014,SE_A14001_015,SE_A14001_016,SE_A14001_017,PCT_SE_A14001_002,PCT_SE_A14001_003,PCT_SE_A14001_004,PCT_SE_A14001_005,PCT_SE_A14001_006,PCT_SE_A14001_007,PCT_SE_A14001_008,PCT_SE_A14001_009,PCT_SE_A14001_010,PCT_SE_A14001_011,PCT_SE_A14001_012,PCT_SE_A14001_013,PCT_SE_A14001_014,PCT_SE_A14001_015,PCT_SE_A14001_016,PCT_SE_A14001_017
509,6037203300,14000US06037203300,Census Tract 2033,"Census Tract 2033, Los Angeles County, California",ca,140,0,ACSSF,4379,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,203300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415,54,77,0,13,43,23,28,58,11,16,28,22,19,12,11,0,13.01,18.55,0.0,3.13,10.36,5.54,6.75,13.98,2.65,3.86,6.75,5.3,4.58,2.89,2.65,0.0

In [9]:
HI.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2346 entries, 0 to 2345
Data columns (total 88 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Geo_FIPS           2346 non-null   int64
 1   Geo_GEOID          2346 non-null   object
 2   Geo_NAME           2346 non-null   object
 3   Geo_QName          2346 non-null   object
 4   Geo_STUSAB         2346 non-null   object
 5   Geo_SUMLEV         2346 non-null   int64
 6   Geo_GEOCOMP        2346 non-null   int64
 7   Geo_FILEID         2346 non-null   object
 8   Geo_LOGRECNO       2346 non-null   int64
 9   Geo_US             0 non-null      float64
 10  Geo_REGION         0 non-null      float64
 11  Geo_DIVISION       0 non-null      float64
 12  Geo_STATECE        0 non-null      float64
 13  Geo_STATE          2346 non-null   int64
 14  Geo_COUNTY         2346 non-null   int64
 15  Geo_COUSUB         0 non-null      float64
 16  Geo_PLACE          0 non-null      float64
 17  Geo_PLACESE        0 non-null      float64
 18  Geo_TRACT          2346 non-null   int64
 19  Geo_BLKGRP         0 non-null      float64
 20  Geo_CONCIT         0 non-null      float64
 21  Geo_AIANHH         0 non-null      float64
 22  Geo_AIANHHFP       0 non-null      float64
 23  Geo_AIHHTLI        0 non-null      float64
 24  Geo_AITSCE         0 non-null      float64
 25  Geo_AITS           0 non-null      float64
 26  Geo_ANRC           0 non-null      float64
 27  Geo_CBSA           0 non-null      float64
 28  Geo_CSA            0 non-null      float64
 29  Geo_METDIV         0 non-null      float64
 30  Geo_MACC           0 non-null      float64
 31  Geo_MEMI           0 non-null      float64
 32  Geo_NECTA          0 non-null      float64
 33  Geo_CNECTA         0 non-null      float64
 34  Geo_NECTADIV       0 non-null      float64
 35  Geo_UA             0 non-null      float64
 36  Geo_UACP           0 non-null      float64
 37  Geo_CDCURR         0 non-null      float64
 38  Geo_SLDU           0 non-null      float64
 39  Geo_SLDL           0 non-null      float64
 40  Geo_VTD            0 non-null      float64
 41  Geo_ZCTA3          0 non-null      float64
 42  Geo_ZCTA5          0 non-null      float64
 43  Geo_SUBMCD         0 non-null      float64
 44  Geo_SDELM          0 non-null      float64
 45  Geo_SDSEC          0 non-null      float64
 46  Geo_SDUNI          0 non-null      float64
 47  Geo_UR             0 non-null      float64
 48  Geo_PCI            0 non-null      float64
 49  Geo_TAZ            0 non-null      float64
 50  Geo_UGA            0 non-null      float64
 51  Geo_BTTR           0 non-null      float64
 52  Geo_BTBG           0 non-null      float64
 53  Geo_PUMA5          0 non-null      float64
 54  Geo_PUMA1          0 non-null      float64
 55  SE_A14001_001      2346 non-null   int64
 56  SE_A14001_002      2346 non-null   int64
 57  SE_A14001_003      2346 non-null   int64
 58  SE_A14001_004      2346 non-null   int64
 59  SE_A14001_005      2346 non-null   int64
 60  SE_A14001_006      2346 non-null   int64
 61  SE_A14001_007      2346 non-null   int64
 62  SE_A14001_008      2346 non-null   int64
 63  SE_A14001_009      2346 non-null   int64
 64  SE_A14001_010      2346 non-null   int64
 65  SE_A14001_011      2346 non-null   int64
 66  SE_A14001_012      2346 non-null   int64
 67  SE_A14001_013      2346 non-null   int64
 68  SE_A14001_014      2346 non-null   int64
 69  SE_A14001_015      2346 non-null   int64
 70  SE_A14001_016      2346 non-null   int64
 71  SE_A14001_017      2346 non-null   int64
 72  PCT_SE_A14001_002  2319 non-null   float64
 73  PCT_SE_A14001_003  2319 non-null   float64
 74  PCT_SE_A14001_004  2319 non-null   float64
 75  PCT_SE_A14001_005  2319 non-null   float64
 76  PCT_SE_A14001_006  2319 non-null   float64
 77  PCT_SE_A14001_007  2319 non-null   float64
 78  PCT_SE_A14001_008  2319 non-null   float64
 79  PCT_SE_A14001_009  2319 non-null   float64
 80  PCT_SE_A14001_010  2319 non-null   float64
 81  PCT_SE_A14001_011  2319 non-null   float64
 82  PCT_SE_A14001_012  2319 non-null   float64
 83  PCT_SE_A14001_013  2319 non-null   float64
 84  PCT_SE_A14001_014  2319 non-null   float64
 85  PCT_SE_A14001_015  2319 non-null   float64
 86  PCT_SE_A14001_016  2319 non-null   float64
 87  PCT_SE_A14001_017  2319 non-null   float64
dtypes: float64(59), int64(24), object(5)
memory usage: 1.6+ MB

In [11]:
HI.Geo_FIPS.head()

0    6037101110
1    6037101122
2    6037101210
3    6037101220
4    6037101300
Name: Geo_FIPS, dtype: int64

In [12]:
HI.Geo_COUNTY.head()

0    37
1    37
2    37
3    37
4    37
Name: Geo_COUNTY, dtype: int64

In [13]:
HI.Geo_STATE.head()

0    6
1    6
2    6
3    6
4    6
Name: Geo_STATE, dtype: int64

In [14]:
HI = pd.read_csv(
    'data/Household Income LA County (2018).csv',
    dtype=
    {
        'Geo_FIPS':str,
        'Geo_STATE':str,
        'Geo_COUNTY': str
    }
)

In [15]:
HI.head()

,Geo_FIPS,Geo_GEOID,Geo_NAME,Geo_QName,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_FILEID,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_PLACESE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_BTTR,Geo_BTBG,Geo_PUMA5,Geo_PUMA1,SE_A14001_001,SE_A14001_002,SE_A14001_003,SE_A14001_004,SE_A14001_005,SE_A14001_006,SE_A14001_007,SE_A14001_008,SE_A14001_009,SE_A14001_010,SE_A14001_011,SE_A14001_012,SE_A14001_013,SE_A14001_014,SE_A14001_015,SE_A14001_016,SE_A14001_017,PCT_SE_A14001_002,PCT_SE_A14001_003,PCT_SE_A14001_004,PCT_SE_A14001_005,PCT_SE_A14001_006,PCT_SE_A14001_007,PCT_SE_A14001_008,PCT_SE_A14001_009,PCT_SE_A14001_010,PCT_SE_A14001_011,PCT_SE_A14001_012,PCT_SE_A14001_013,PCT_SE_A14001_014,PCT_SE_A14001_015,PCT_SE_A14001_016,PCT_SE_A14001_017
0,6037101110,14000US06037101110,Census Tract 1011.10,"Census Tract 1011.10, Los Angeles County, Cali...",ca,140,0,ACSSF,3870,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,101110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1596,110,97,70,76,123,96,54,78,88,64,126,277,91,93,109,44,6.89,6.08,4.39,4.76,7.71,6.02,3.38,4.89,5.51,4.01,7.89,17.36,5.70,5.83,6.83,2.76
1,6037101122,14000US06037101122,Census Tract 1011.22,"Census Tract 1011.22, Los Angeles County, Cali...",ca,140,0,ACSSF,3871,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,101122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1256,52,18,0,15,39,38,7,40,23,62,186,232,114,105,133,192,4.14,1.43,0.00,1.19,3.11,3.03,0.56,3.18,1.83,4.94,14.81,18.47,9.08,8.36,10.59,15.29
2,6037101210,14000US06037101210,Census Tract 1012.10,"Census Tract 1012.10, Los Angeles County, Cali...",ca,140,0,ACSSF,3872,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,101210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2321,285,140,335,69,223,145,61,95,220,128,147,225,96,67,14,71,12.28,6.03,14.43,2.97,9.61,6.25,2.63,4.09,9.48,5.51,6.33,9.69,4.14,2.89,0.60,3.06
3,6037101220,14000US06037101220,Census Tract 1012.20,"Census Tract 1012.20, Los Angeles County, Cali...",ca,140,0,ACSSF,3873,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,101220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1294,65,104,160,56,22,133,60,118,123,53,75,88,110,45,43,39,5.02,8.04,12.36,4.33,1.70,10.28,4.64,9.12,9.51,4.10,5.80,6.80,8.50,3.48,3.32,3.01
4,6037101300,14000US06037101300,Census Tract 1013,"Census Tract 1013, Los Angeles County, California",ca,140,0,ACSSF,3874,NaN,NaN,NaN,NaN,6,37,NaN,NaN,NaN,101300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1435,75,14,69,36,29,23,18,123,49,87,80,200,146,107,195,184,5.23,0.98,4.81,2.51,2.02,1.60,1.25,8.57,3.41,6.06,5.57,13.94,10.17,7.46,13.59,12.82

In [16]:
HI.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2346 entries, 0 to 2345
Data columns (total 88 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Geo_FIPS           2346 non-null   object
 1   Geo_GEOID          2346 non-null   object
 2   Geo_NAME           2346 non-null   object
 3   Geo_QName          2346 non-null   object
 4   Geo_STUSAB         2346 non-null   object
 5   Geo_SUMLEV         2346 non-null   int64
 6   Geo_GEOCOMP        2346 non-null   int64
 7   Geo_FILEID         2346 non-null   object
 8   Geo_LOGRECNO       2346 non-null   int64
 9   Geo_US             0 non-null      float64
 10  Geo_REGION         0 non-null      float64
 11  Geo_DIVISION       0 non-null      float64
 12  Geo_STATECE        0 non-null      float64
 13  Geo_STATE          2346 non-null   object
 14  Geo_COUNTY         2346 non-null   object
 15  Geo_COUSUB         0 non-null      float64
 16  Geo_PLACE          0 non-null      float64
 17  Geo_PLACESE        0 non-null      float64
 18  Geo_TRACT          2346 non-null   int64
 19  Geo_BLKGRP         0 non-null      float64
 20  Geo_CONCIT         0 non-null      float64
 21  Geo_AIANHH         0 non-null      float64
 22  Geo_AIANHHFP       0 non-null      float64
 23  Geo_AIHHTLI        0 non-null      float64
 24  Geo_AITSCE         0 non-null      float64
 25  Geo_AITS           0 non-null      float64
 26  Geo_ANRC           0 non-null      float64
 27  Geo_CBSA           0 non-null      float64
 28  Geo_CSA            0 non-null      float64
 29  Geo_METDIV         0 non-null      float64
 30  Geo_MACC           0 non-null      float64
 31  Geo_MEMI           0 non-null      float64
 32  Geo_NECTA          0 non-null      float64
 33  Geo_CNECTA         0 non-null      float64
 34  Geo_NECTADIV       0 non-null      float64
 35  Geo_UA             0 non-null      float64
 36  Geo_UACP           0 non-null      float64
 37  Geo_CDCURR         0 non-null      float64
 38  Geo_SLDU           0 non-null      float64
 39  Geo_SLDL           0 non-null      float64
 40  Geo_VTD            0 non-null      float64
 41  Geo_ZCTA3          0 non-null      float64
 42  Geo_ZCTA5          0 non-null      float64
 43  Geo_SUBMCD         0 non-null      float64
 44  Geo_SDELM          0 non-null      float64
 45  Geo_SDSEC          0 non-null      float64
 46  Geo_SDUNI          0 non-null      float64
 47  Geo_UR             0 non-null      float64
 48  Geo_PCI            0 non-null      float64
 49  Geo_TAZ            0 non-null      float64
 50  Geo_UGA            0 non-null      float64
 51  Geo_BTTR           0 non-null      float64
 52  Geo_BTBG           0 non-null      float64
 53  Geo_PUMA5          0 non-null      float64
 54  Geo_PUMA1          0 non-null      float64
 55  SE_A14001_001      2346 non-null   int64
 56  SE_A14001_002      2346 non-null   int64
 57  SE_A14001_003      2346 non-null   int64
 58  SE_A14001_004      2346 non-null   int64
 59  SE_A14001_005      2346 non-null   int64
 60  SE_A14001_006      2346 non-null   int64
 61  SE_A14001_007      2346 non-null   int64
 62  SE_A14001_008      2346 non-null   int64
 63  SE_A14001_009      2346 non-null   int64
 64  SE_A14001_010      2346 non-null   int64
 65  SE_A14001_011      2346 non-null   int64
 66  SE_A14001_012      2346 non-null   int64
 67  SE_A14001_013      2346 non-null   int64
 68  SE_A14001_014      2346 non-null   int64
 69  SE_A14001_015      2346 non-null   int64
 70  SE_A14001_016      2346 non-null   int64
 71  SE_A14001_017      2346 non-null   int64
 72  PCT_SE_A14001_002  2319 non-null   float64
 73  PCT_SE_A14001_003  2319 non-null   float64
 74  PCT_SE_A14001_004  2319 non-null   float64
 75  PCT_SE_A14001_005  2319 non-null   float64
 76  PCT_SE_A14001_006  2319 non-null   float64
 77  PCT_SE_A14001_007  2319 non-null   float64
 78  PCT_SE_A14001_008  2319 non-null   float64
 79  PCT_SE_A14001_009  2319 non-null   float64
 80  PCT_SE_A14001_010  2319 non-null   float64
 81  PCT_SE_A14001_011  2319 non-null   float64
 82  PCT_SE_A14001_012  2319 non-null   float64
 83  PCT_SE_A14001_013  2319 non-null   float64
 84  PCT_SE_A14001_014  2319 non-null   float64
 85  PCT_SE_A14001_015  2319 non-null   float64
 86  PCT_SE_A14001_016  2319 non-null   float64
 87  PCT_SE_A14001_017  2319 non-null   float64
dtypes: float64(59), int64(21), object(8)
memory usage: 1.6+ MB